module.exports = {
    vegetables: [
      { key: "tomato", en: "Tomato", hi: "टमाटर", kn: "ಟೊಮೇಟೊ", mr: "टोमॅटो" },
      { key: "potato", en: "Potato", hi: "आलू", kn: "ಆಲೂಗಡ್ಡೆ", mr: "बटाटा" },
      { key: "onion", en: "Onion", hi: "प्याज", kn: "ಈರುಳ್ಳಿ", mr: "कांदा" },
      { key: "brinjal", en: "Brinjal (Eggplant)", hi: "बैंगन", kn: "ಬದನೆಕಾಯಿ", mr: "वांगी" },
      { key: "okra", en: "Okra (Lady Finger)", hi: "भिंडी", kn: "ಬೆಂಡೆಕಾಯಿ", mr: "भेंडी" },
      { key: "cabbage", en: "Cabbage", hi: "पत्ता गोभी", kn: "ಎಲೆಕೋಸು", mr: "कोबी" },
      { key: "cauliflower", en: "Cauliflower", hi: "फूलगोभी", kn: "ಹೂಕೋಸು", mr: "फूलकोबी" },
      { key: "carrot", en: "Carrot", hi: "गाजर", kn: "ಗಾಜರ", mr: "गाजर" },
      { key: "beetroot", en: "Beetroot", hi: "चुकंदर", kn: "ಬೀಟ್ರೂಟ್", mr: "बीट" },
      { key: "radish", en: "Radish", hi: "मूली", kn: "ಮೂಲಂಗಿ", mr: "मुळा" },
      { key: "spinach", en: "Spinach", hi: "पालक", kn: "ಪಾಲಕ್", mr: "पालक" },
      { key: "bottle_gourd", en: "Bottle Gourd", hi: "लौकी", kn: "ಸೊರೆಕಾಯಿ", mr: "दुधी" },
      { key: "bitter_gourd", en: "Bitter Gourd", hi: "करेला", kn: "ಹಾಗಲಕಾಯಿ", mr: "कारले" },
      { key: "ridge_gourd", en: "Ridge Gourd", hi: "तोरी", kn: "ಹೀರೇಕಾಯಿ", mr: "दोडका" },
      { key: "pumpkin", en: "Pumpkin", hi: "कद्दू", kn: "ಕುಂಬಳಕಾಯಿ", mr: "भोपळा" },
      { key: "cucumber", en: "Cucumber", hi: "खीरा", kn: "ಸೌತೆಕಾಯಿ", mr: "काकडी" },
      { key: "green_peas", en: "Green Peas", hi: "मटर", kn: "ಹುರಳಿಕಾಯಿ", mr: "मटार" },
      { key: "french_beans", en: "French Beans", hi: "फ्रेंच बीन्स", kn: "ಹರಿತೋಳ", mr: "फ्रेंच बीन्स" },
      { key: "capsicum", en: "Capsicum (Bell Pepper)", hi: "शिमला मिर्च", kn: "ದೊಡ್ಡ ಮೆಣಸು", mr: "शिमला मिरची" },
      { key: "green_chilli", en: "Green Chilli", hi: "हरी मिर्च", kn: "ಹಸಿರು ಮೆಣಸು", mr: "हिरवी मिरची" },
      { key: "garlic", en: "Garlic", hi: "लहसुन", kn: "ಬೆಳ್ಳುಳ್ಳಿ", mr: "लसूण" },
      { key: "ginger", en: "Ginger", hi: "अदरक", kn: "ಶುಂಠಿ", mr: "आले" },
      { key: "sweet_potato", en: "Sweet Potato", hi: "शकरकंद", kn: "ಸಿಹಿ ಆಲೂಗಡ್ಡೆ", mr: "राताळे" },
      { key: "turnip", en: "Turnip", hi: "शलगम", kn: "ನವಿಲುಕೋಸು", mr: "शलगम" },
      { key: "broccoli", en: "Broccoli", hi: "ब्रोकली", kn: "ಬ್ರೋಕೋಲಿ", mr: "ब्रोकली" },
      { key: "zucchini", en: "Zucchini", hi: "तोरी", kn: "ಸುಕ್ಕಿನಿ", mr: "झुकीनी" },
      { key: "lettuce", en: "Lettuce", hi: "सलाद पत्ता", kn: "ಲೆಟ್ಯೂಸ್", mr: "लेट्यूस" },
      { key: "drumstick", en: "Drumstick (Moringa)", hi: "सहजन", kn: "ನುಗಗೆಕಾಯಿ", mr: "शेवगा" },
      { key: "tinda", en: "Tinda (Apple Gourd)", hi: "टिंडा", kn: "ಟಿಂಡಾ", mr: "टिंडा" },
      { key: "cluster_beans", en: "Cluster Beans (Guar)", hi: "ग्वार फली", kn: "ಗೊರಿಕಾಯಿ", mr: "गवार" },
      { key: "yam", en: "Yam", hi: "जिमीकंद", kn: "ಸೂರಣ", mr: "सुरण" }
    ],
    fruits: [
      { key: "mango", en: "Mango", hi: "आम", kn: "ಮಾವು", mr: "आंबा" },
      { key: "banana", en: "Banana", hi: "केला", kn: "ಬಾಳೆಹಣ್ಣು", mr: "केळं" },
      { key: "apple", en: "Apple", hi: "सेब", kn: "ಸೇಬು", mr: "सफरचंद" },
      { key: "orange", en: "Orange", hi: "संतरा", kn: "ಕಿತ್ತಳೆ", mr: "संत्रा" },
      { key: "papaya", en: "Papaya", hi: "पपीता", kn: "ಪಪ್ಪಾಯಿ", mr: "पपई" },
      { key: "guava", en: "Guava", hi: "अमरूद", kn: "ಸೀಬೆ ಹಣ್ಣು", mr: "पेरू" },
      { key: "pomegranate", en: "Pomegranate", hi: "अनार", kn: "ದಾಳಿಂಬೆ", mr: "डाळिंब" },
      { key: "watermelon", en: "Watermelon", hi: "तरबूज", kn: "ಕಲ್ಲಂಗಡಿ", mr: "कलिंगड" },
      { key: "muskmelon", en: "Muskmelon", hi: "खरबूजा", kn: "ಸೌತೆಕಾಯಿ", mr: "साखरटर" },
      { key: "grapes", en: "Grapes", hi: "अंगूर", kn: "ದ್ರಾಕ್ಷಿ", mr: "द्राक्ष" },
      { key: "pineapple", en: "Pineapple", hi: "अनानास", kn: "ಅನಾನಸ್", mr: "अननस" },
      { key: "sapota", en: "Sapota (Chikoo)", hi: "चीकू", kn: "ಚಿಕ್ಕು", mr: "चिकू" },
      { key: "lemon", en: "Lemon", hi: "नींबू", kn: "ನಿಂಬೆ", mr: "लिंबू" },
      { key: "litchi", en: "Litchi", hi: "लीची", kn: "ಲಿಚಿ", mr: "लीची" },
      { key: "pear", en: "Pear", hi: "नाशपाती", kn: "ನಾಶ್ಪತಿ", mr: "नाशपाती" },
      { key: "plum", en: "Plum", hi: "आलूबुखारा", kn: "ಪ್ಲಮ್", mr: "आलुबुखारा" },
      { key: "peach", en: "Peach", hi: "आड़ू", kn: "ಪೀಚ್", mr: "पीच" },
      { key: "apricot", en: "Apricot", hi: "खुबानी", kn: "ಜರದಾಳು", mr: "जर्दाळू" },
      { key: "custard_apple", en: "Custard Apple (Sitaphal)", hi: "सीताफल", kn: "ಸೀತಾಫಲ", mr: "सीताफळ" },
      { key: "jackfruit", en: "Jackfruit", hi: "कटहल", kn: "ಹಲಸು", mr: "फणस" },
      { key: "strawberry", en: "Strawberry", hi: "स्ट्रॉबेरी", kn: "ಸ್ಟ್ರಾಬೆರಿ", mr: "स्ट्रॉबेरी" },
      { key: "blueberry", en: "Blueberry", hi: "ब्लूबेरी", kn: "ಬ್ಲೂಬೆರಿ", mr: "ब्लूबेरी" },
      { key: "raspberry", en: "Raspberry", hi: "रास्पबेरी", kn: "ರಾಸ್ಪ್ಬೆರಿ", mr: "रास्पबेरी" },
      { key: "cherry", en: "Cherry", hi: "चेरी", kn: "ಚೆರಿ", mr: "चेरी" },
      { key: "kiwi", en: "Kiwi", hi: "कीवी", kn: "ಕಿವಿ", mr: "कीवी" },
      { key: "avocado", en: "Avocado", hi: "एवोकाडो", kn: "ಅವೊಕಾಡೋ", mr: "ऍवोकाडो" },
      { key: "fig", en: "Fig", hi: "अंजीर", kn: "ಅಂಜೂರ", mr: "अंजीर" },
      { key: "dates", en: "Dates", hi: "खजूर", kn: "ಖರ್ಜೂರ", mr: "खजूर" },
      { key: "coconut", en: "Coconut", hi: "नारियल", kn: "ತೆಂಗಿನಕಾಯಿ", mr: "नारळ" },
      { key: "gooseberry", en: "Gooseberry (Amla)", hi: "आंवला", kn: "ನೆಲ್ಲಿಕಾಯಿ", mr: "आवळा" }
    ],
    grains: [
      { key: "rice", en: "Rice (Paddy)", hi: "चावल", kn: "ಅಕ್ಕಿ", mr: "तांदूळ" },
      { key: "wheat", en: "Wheat", hi: "गेहूं", kn: "ಗೋಧಿ", mr: "गहू" },
      { key: "maize", en: "Maize (Corn)", hi: "मक्का", kn: "ಜೋಳ", mr: "मका" },
      { key: "barley", en: "Barley", hi: "जौ", kn: "ಯವ", mr: "बार्ली" },
      { key: "oats", en: "Oats", hi: "जई", kn: "ಓಟ್ಸ್", mr: "ओट्स" },
      { key: "bajra", en: "Bajra (Pearl Millet)", hi: "बाजरा", kn: "ಸಜ್ಜೆ", mr: "बाजरी" },
      { key: "jowar", en: "Jowar (Sorghum)", hi: "ज्वार", kn: "ಜೋಳ", mr: "ज्वारी" },
      { key: "ragi", en: "Ragi (Finger Millet)", hi: "रागी", kn: "ರಾಗಿ", mr: "नाचणी" },
      { key: "foxtail_millet", en: "Foxtail Millet", hi: "कंगनी", kn: "ನವರಿ", mr: "कांगणी" },
      { key: "little_millet", en: "Little Millet", hi: "सामा", kn: "ಸಾಮೆ", mr: "साव" },
      { key: "kodo_millet", en: "Kodo Millet", hi: "कोदो", kn: "ಹರಕ", mr: "कोद्रा" },
      { key: "barnyard_millet", en: "Barnyard Millet", hi: "सांवा", kn: "ಒಡಲು", mr: "सांवा" },
      { key: "proso_millet", en: "Proso Millet", hi: "चेना", kn: "ಬ್ರಹ್ಮ", mr: "वरई" },
      { key: "buckwheat", en: "Buckwheat", hi: "कुट्टू", kn: "ಬಕ್‌ವೀಟ್", mr: "कुटू" },
      { key: "quinoa", en: "Quinoa", hi: "क्विनोआ", kn: "ಕ್ವಿನೋವಾ", mr: "क्विनोआ" },
      { key: "amaranth", en: "Amaranth", hi: "राजगिरा", kn: "ಹರಳೆ", mr: "राजगिरा" },
      { key: "rye", en: "Rye", hi: "राई", kn: "ರೈ", mr: "राई" },
      { key: "teff", en: "Teff", hi: "तेफ", kn: "ಟೆಫ್", mr: "तेफ" },
      { key: "spelt", en: "Spelt", hi: "स्पेल्ट", kn: "ಸ್ಪೆಲ್ಟ್", mr: "स्पेल्ट" }
    ],
    pulses: [
      { key: "masoor_dal", en: "Lentils (Masoor Dal)", hi: "मसूर दाल", kn: "ಮಸೂರ ದಾಲ್", mr: "मसूर डाळ" },
      { key: "chickpeas", en: "Chickpeas (Chana)", hi: "चना", kn: "ಕಡಲೆಕಾಯಿ", mr: "हरभरा" },
      { key: "moong_dal", en: "Green Gram (Moong Dal)", hi: "मूंग दाल", kn: "ಹೆಸರುಕಾಳು", mr: "मुग डाळ" },
      { key: "urad_dal", en: "Black Gram (Urad Dal)", hi: "उड़द दाल", kn: "ಉದ್ದಿನಕಾಳು", mr: "उडीद डाळ" },
      { key: "toor_dal", en: "Pigeon Pea (Toor Dal)", hi: "अरहर दाल", kn: "ತೊಗರಿ ಬೇಳೆ", mr: "तूर डाळ" },
      { key: "peas_dry", en: "Peas (Dry)", hi: "सूखी मटर", kn: "ಒಣ ಹುರಳಿಕಾಯಿ", mr: "सुक्या मटार" },
      { key: "rajma", en: "Kidney Beans (Rajma)", hi: "राजमा", kn: "ರಾಜ್ಮಾ", mr: "राजमा" },
      { key: "cowpea", en: "Cowpea (Lobia)", hi: "लोबिया", kn: "ಅಲಸಂದೆ", mr: "चवळी" },
      { key: "horse_gram", en: "Horse Gram (Kulthi)", hi: "कुल्थी", kn: "ಹುರುಳಿಕಾಳು", mr: "कुळीथ" },
      { key: "moth_bean", en: "Moth Bean (Matki)", hi: "मटकी", kn: "ಮಟ್ಕಿ", mr: "मटकी" }
    ],
    oilseeds: [
      { key: "groundnut", en: "Groundnut (Peanut)", hi: "मूंगफली", kn: "ಶೇಂಗಾ", mr: "शेंगदाणा" },
      { key: "soybean", en: "Soybean", hi: "सोयाबीन", kn: "ಸೊಯಾಬೀನ್", mr: "सोयाबीन" },
      { key: "sunflower_seeds", en: "Sunflower Seeds", hi: "सूरजमुखी बीज", kn: "ಸೂರ್ಯಕಾಂತಿ ಬೀಜ", mr: "सूर्यफूल बिया" },
      { key: "sesame_seeds", en: "Sesame Seeds", hi: "तिल", kn: "ಎಳ್ಳು", mr: "तीळ" },
      { key: "flax_seeds", en: "Flax Seeds", hi: "अलसी", kn: "ಅಗಸೆ ಬೀಜ", mr: "जवस" },
      { key: "mustard_seeds", en: "Mustard Seeds", hi: "सरसों", kn: "ಸಾಸಿವೆ", mr: "मोहरी" },
      { key: "pumpkin_seeds", en: "Pumpkin Seeds", hi: "कद्दू बीज", kn: "ಕುಂಬಳಕಾಯಿ ಬೀಜ", mr: "भोपळा बिया" }
    ],
    spices: [
      { key: "turmeric", en: "Turmeric", hi: "हल्दी", kn: "ಅರಿಶಿನ", mr: "हळद" },
      { key: "chilli_powder", en: "Chilli Powder", hi: "मिर्च पाउडर", kn: "ಮೆಣಸಿನ ಪುಡಿ", mr: "मिरची पावडर" },
      { key: "coriander_seeds", en: "Coriander Seeds", hi: "धनिया", kn: "ಕೊತ್ತಂಬರಿ ಬೀಜ", mr: "धणे" },
      { key: "cumin_seeds", en: "Cumin Seeds", hi: "जीरा", kn: "ಜೀರಿಗೆ", mr: "जिरे" },
      { key: "black_pepper", en: "Black Pepper", hi: "काली मिर्च", kn: "ಮೆಣಸು", mr: "मिरी" },
      { key: "cardamom", en: "Cardamom", hi: "इलायची", kn: "ಏಲಕ್ಕಿ", mr: "वेलची" },
      { key: "cloves", en: "Cloves", hi: "लौंग", kn: "ಲವಂಗ", mr: "लवंग" },
      { key: "cinnamon", en: "Cinnamon", hi: "दालचीनी", kn: "ಚಕ್ಕೆ", mr: "दालचिनी" },
      { key: "fenugreek_seeds", en: "Fenugreek Seeds", hi: "मेथी", kn: "ಮೆಂತ್ಯೆ", mr: "मेथी" },
      { key: "fennel_seeds", en: "Fennel Seeds", hi: "सौंफ", kn: "ಸೋಪು", mr: "बडीशेप" },
      { key: "asafoetida", en: "Asafoetida (Hing)", hi: "हींग", kn: "ಇಂಗು", mr: "हिंग" },
      { key: "curry_leaves", en: "Curry Leaves", hi: "करी पत्ता", kn: "ಕರಿಬೇವು", mr: "कढीपत्ता" },
      { key: "bay_leaf", en: "Bay Leaf", hi: "तेज पत्ता", kn: "ಬೇ ಲೀಫ್", mr: "तमालपत्र" },
      { key: "saffron", en: "Saffron", hi: "केसर", kn: "ಕೇಸರಿ", mr: "केशर" }
    ],
    dairy: [
      { key: "milk", en: "Milk", hi: "दूध", kn: "ಹಾಲು", mr: "दूध" },
      { key: "curd", en: "Curd (Yogurt)", hi: "दही", kn: "ಮಜ್ಜಿಗೆ", mr: "दही" },
      { key: "paneer", en: "Paneer (Cottage Cheese)", hi: "पनीर", kn: "ಪನೀರ್", mr: "पनीर" },
      { key: "ghee", en: "Ghee", hi: "घी", kn: "ತುಪ್ಪ", mr: "तूप" },
      { key: "butter", en: "Butter", hi: "मक्खन", kn: "ಬೆಣ್ಣೆ", mr: "लोणी" },
      { key: "cheese", en: "Cheese", hi: "चीज़", kn: "ಚೀಸ್", mr: "चीज" },
      { key: "buttermilk", en: "Buttermilk", hi: "छाछ", kn: "ಮಜ್ಜಿಗೆ", mr: "मट्ठा" },
      { key: "cream", en: "Cream", hi: "मलाई", kn: "ಹಾಲಿನ ಸಣ್ಣ", mr: "साय" }
    ]
  };